spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/akhil3kumar/fraud-remittance.git
          default-label: main
#          clone-on-start: true
          search-paths: FraudRemittance_API/configuration-repository

server:
  port: 8888

input:
  record.csv