spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

security:
  jwt:
    expiration-time: 900000
    refresh-expiration-time: 604800000